<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared.Exception.Abstraction\Shared.Exception.Abstraction.csproj" />
    <ProjectReference Include="..\Shared.Versioning.Abstraction\Shared.Versioning.Abstraction.csproj" />
  </ItemGroup>

</Project>
