// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.APExceptionHandlerMiddleware.InvokeAsync(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "HAA0101:Array allocation for params parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.Registration.UseAPRequestResponseLogger(Microsoft.AspNetCore.Builder.WebApplication,System.Action{AP.Shared.Middlewares.TraceMiddlewareConfig})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.Extensions.ExceptionExtensions.GetErrorsFromHierarchy(System.Exception,System.Func{System.Exception,System.Exception})~System.Collections.Generic.IDictionary{System.String,System.String}")]
[assembly: SuppressMessage("Major Code Smell", "S1854:Unused assignments should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.Extensions.ExceptionExtensions.GetErrorsFromHierarchy(System.Exception,System.Func{System.Exception,System.Exception})~System.Collections.Generic.IDictionary{System.String,System.String}")]
[assembly: SuppressMessage("Performance", "CA1806:Do not ignore method results", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.APExceptionHandlerMiddleware.InvokeAsync(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:AP.Shared.Middlewares.LoggingMiddlewareConfig.ExcludedLogPaths")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.Extensions.HttpContextExtensions.GetServiceName(Microsoft.AspNetCore.Http.HttpContext)~System.String")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:AP.Shared.Middlewares.APExceptionHandlerMiddleware")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:AP.Shared.Middlewares.APLoggingMiddleware")]
[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:AP.Shared.Middlewares.ApMeasurementMiddleware")]
[assembly: SuppressMessage("Performance", "HAA0101:Array allocation for params parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.Registration.UseAPRequestResponseLogger(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.Extensions.Configuration.IConfiguration,System.Action{AP.Shared.Middlewares.TraceMiddlewareConfig})")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.Extensions.HttpContextExtensions.GetActionName(Microsoft.AspNetCore.Http.HttpContext)~System.String")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.Extensions.HttpContextExtensions.GetControllerName(Microsoft.AspNetCore.Http.HttpContext)~System.String")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.APLoggingMiddleware.GetInputParamsAsync(Microsoft.AspNetCore.Http.HttpRequest)~System.Threading.Tasks.ValueTask{System.Object}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.APLoggingMiddleware.GetInputParamsAsync(Microsoft.AspNetCore.Http.HttpRequest,System.Int32)~System.Threading.Tasks.ValueTask{System.Object}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.APLoggingMiddleware.GetInputParamsAsync(Microsoft.AspNetCore.Http.HttpRequest,AP.Shared.Middlewares.TraceMiddlewareConfig)~System.Threading.Tasks.ValueTask{System.Object}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.APLoggingMiddleware.GetInputParamsAsync(Microsoft.AspNetCore.Http.HttpRequest,AP.Shared.Middlewares.LoggingMiddlewareConfig)~System.Threading.Tasks.ValueTask{System.Object}")]
[assembly: SuppressMessage("Performance", "HAA0101:Array allocation for params parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.Registration.UseAPRequestResponseLogger(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.Extensions.Configuration.IConfiguration,System.Action{AP.Shared.Middlewares.LoggingMiddlewareConfig})")]
[assembly: SuppressMessage("Performance", "HAA0101:Array allocation for params parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.Registration.UseAPRequestResponseLogger(Microsoft.AspNetCore.Builder.WebApplication,System.Action{AP.Shared.Middlewares.LoggingMiddlewareConfig})")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:AP.Shared.Middlewares.APLoggingMiddleware.GetInputParamsAsync(Microsoft.AspNetCore.Http.HttpRequest,AP.Shared.Middlewares.LoggingMiddlewareConfig,System.Threading.CancellationToken)~System.Threading.Tasks.ValueTask{System.Object}")]
