// <auto-generated />
using Infrastructure.Data.Repository.EfCore.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

#nullable disable

namespace Infrastructure.Data.Repository.EfCore.Migrations.BillingDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251019071815_Modify_Billing_And_Installment")]
    partial class Modify_Billing_And_Installment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttachmentCategory")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FileReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("Attachment", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.BackgroundJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "JobId" }, "IX_BackgroundJob_JobId")
                        .IsUnique();

                    b.ToTable("BackgroundJob", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Billing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AdditionsAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<string>("AdditionsDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<string>("CheckSum")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContractIds")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("CreditorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DebtorId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DeductionsAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<string>("DeductionsDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromBusinessIdentityId")
                        .HasColumnType("int");

                    b.Property<int>("GracePeriod")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MainContractId")
                        .HasColumnType("int");

                    b.Property<byte>("PeriodType")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("PreviousCreditAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal>("PreviousDebitAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal>("PreviousPenaltyAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("ToBusinessIdentityId")
                        .HasColumnType("int");

                    b.Property<bool>("Transferred")
                        .HasColumnType("bit");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreditorId" }, "IX_Billing_CreditorId");

                    b.HasIndex(new[] { "DebtorId" }, "IX_Billing_DebtorId");

                    b.HasIndex(new[] { "FromBusinessIdentityId" }, "IX_Billing_FromBusinessIdentityId");

                    b.HasIndex(new[] { "TenantId" }, "IX_Billing_TenantId");

                    b.HasIndex(new[] { "ToBusinessIdentityId" }, "IX_Billing_ToBusinessIdentityId");

                    b.ToTable("Billing", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.BillingPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<long>("BillingId")
                        .HasColumnType("bigint");

                    b.Property<string>("CheckSum")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BillingId" }, "IX_BillingPayment_BillingId");

                    b.ToTable("BillingPayment", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BusinessIdentity", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Facilitator", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsTenant")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId" }, "IX_Facilitator_TenantId");

                    b.ToTable("Facilitator", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.FinancialDocument", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal>("CashAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<string>("CheckSum")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromBusinessIdentityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MerchantBranchId")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("PaymentGatewayType")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("PrepaymentAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<string>("RefundDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte?>("RefundReason")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("RefundType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int?>("TenantMerchantContractId")
                        .HasColumnType("int");

                    b.Property<int?>("TenantPlatformContractId")
                        .HasColumnType("int");

                    b.Property<int>("ToBusinessIdentityId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FromBusinessIdentityId" }, "IX_FinancialDocument_FromBusinessIdentityId");

                    b.HasIndex(new[] { "MerchantBranchId" }, "IX_FinancialDocument_MerchantBranchId");

                    b.HasIndex(new[] { "ParentId" }, "IX_FinancialDocument_ParentId");

                    b.HasIndex(new[] { "TenantId" }, "IX_FinancialDocument_TenantId");

                    b.HasIndex(new[] { "TenantMerchantContractId" }, "IX_FinancialDocument_TenantMerchantContractId");

                    b.HasIndex(new[] { "TenantPlatformContractId" }, "IX_FinancialDocument_TenantPlatformContractId");

                    b.HasIndex(new[] { "ToBusinessIdentityId" }, "IX_FinancialDocument_ToBusinessIdentityId");

                    b.ToTable("FinancialDocument", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Financier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsTenant")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId" }, "IX_Financier_TenantId");

                    b.ToTable("Financier", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Guarantor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsTenant")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId" }, "IX_Guarantor_TenantId");

                    b.ToTable("Guarantor", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Installment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal>("CashAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<string>("CheckSum")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FinancialDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int>("FromBusinessIdentityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("PrepaymentAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("ToBusinessIdentityId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FinancialDocumentId" }, "IX_Installment_FinancialDocumentId");

                    b.HasIndex(new[] { "FromBusinessIdentityId" }, "IX_Installment_FromBusinessIdentityId");

                    b.HasIndex(new[] { "TenantId" }, "IX_Installment_TenantId");

                    b.HasIndex(new[] { "ToBusinessIdentityId" }, "IX_Installment_ToBusinessIdentityId");

                    b.ToTable("Installment", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<byte>("SaleType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Merchant", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.MerchantBilling", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PurchaseTransactionsAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal>("PurchaseTransactionsCalculatedCommission")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal>("PurchaseTransactionsCommission")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal>("RefundedTransactionsAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal>("RefundedTransactionsCommission")
                        .HasColumnType("decimal(32, 10)");

                    b.HasKey("Id");

                    b.ToTable("MerchantBilling", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.MerchantBranch", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsMerchant")
                        .HasColumnType("bit");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<long>("TerminalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MerchantId" }, "IX_MerchantBranch_MerchantId");

                    b.ToTable("MerchantBranch", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.MerchantInstallment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("TenantMerchantContractId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantMerchantContractId" }, "IX_MerchantInstallment_TenantMerchantContractId");

                    b.ToTable("MerchantInstallment", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ParentId" }, "IX_Organization_ParentId");

                    b.HasIndex(new[] { "TenantId" }, "IX_Organization_TenantId");

                    b.ToTable("Organization", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Outbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublishTryCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Outbox", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte>("ProviderType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Provider", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BrandName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CreditProjectName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("InternalProjectManagerName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Tenant", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantIpgSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IpgType")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId" }, "IX_TenantIpgSetting_TenantId");

                    b.ToTable("TenantIpgSetting", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantMerchantContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillingBreak")
                        .HasColumnType("int");

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("int");

                    b.Property<byte>("BillingPeriodType")
                        .HasColumnType("tinyint");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("CommissionCalculationType")
                        .HasColumnType("int");

                    b.Property<int?>("CommissionDeductionMethodType")
                        .HasColumnType("int");

                    b.Property<string>("CommissionReferenceTypes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DailyBillingOriginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnamadLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FixedAmountCommission")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("FixedPercentageCommission")
                        .HasColumnType("decimal(6, 3)");

                    b.Property<string>("GuaranteeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte?>("GuaranteeType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("InstallmentsCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("InterestPercentage")
                        .HasColumnType("decimal(6, 3)");

                    b.Property<string>("InterestReferenceTypes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InternetBusinessLicenseLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsCommissionExchanged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<byte>("PaymentMethodType")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("PeriodMaxCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("PeriodMinCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<byte>("SettlementType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TieredCommissions")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("TransactionMaxCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("TransactionMinCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MerchantId" }, "IX_TenantMerchantContract_MerchantId");

                    b.HasIndex(new[] { "ParentId" }, "IX_TenantMerchantContract_ParentId");

                    b.HasIndex(new[] { "TenantId" }, "IX_TenantMerchantContract_TenantId");

                    b.ToTable("TenantMerchantContract", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantPlatformContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("int");

                    b.Property<byte>("BillingPeriodType")
                        .HasColumnType("tinyint");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("CommissionCalculationType")
                        .HasColumnType("int");

                    b.Property<string>("CommissionReferenceTypes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DailyBillingOriginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("FeeCalculationType")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("FixedAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("FixedAmountCommission")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("FixedPercentageCommission")
                        .HasColumnType("decimal(6, 3)");

                    b.Property<int?>("GracePeriod")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PenaltyPercent")
                        .HasColumnType("decimal(6, 3)");

                    b.Property<decimal?>("PeriodMaxCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("PeriodMinCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("TenantIpgSettingId")
                        .HasColumnType("int");

                    b.Property<string>("TieredCommissions")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("TransactionMaxCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("TransactionMinCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId" }, "IX_TenantPlatformContract_TenantId");

                    b.HasIndex(new[] { "TenantIpgSettingId" }, "IX_TenantPlatformContract_TenantIpgSettingId");

                    b.ToTable("TenantPlatformContract", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantPlatformContractFacilitator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacilitatorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FixedAmountCommissionPercentage")
                        .HasColumnType("decimal(6, 3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte?>("PaymentMethodType")
                        .HasColumnType("tinyint");

                    b.Property<int>("TenantPlatformContractId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TransactionsCommissionPercentage")
                        .HasColumnType("decimal(6, 3)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FacilitatorId" }, "IX_TenantPlatformContractFacilitator_FacilitatorId");

                    b.HasIndex(new[] { "TenantPlatformContractId" }, "IX_TenantPlatformContractFacilitator_TenantPlatformContractId");

                    b.ToTable("TenantPlatformContractFacilitator", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantPlatformContractProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("TenantPlatformContractId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProviderId" }, "IX_TenantPlatformContractProvider_ProviderId");

                    b.HasIndex(new[] { "TenantPlatformContractId" }, "IX_TenantPlatformContractProvider_TenantPlatformContractId");

                    b.ToTable("TenantPlatformContractProvider", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.WalletContract", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("RootParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int?>("TenantIpgSettingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId" }, "IX_WalletContract_TenantId");

                    b.HasIndex(new[] { "TenantIpgSettingId" }, "IX_WalletContract_TenantIpgSettingId");

                    b.ToTable("WalletContract", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.WalletContractFacilitator", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("CommissionCalculationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacilitatorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FixedAmountCommission")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("FixedPercentageCommission")
                        .HasColumnType("decimal(6, 3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte?>("PaymentMethodType")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("PeriodMaxCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("PeriodMinCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<string>("PortionTypes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieredCommissions")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("TransactionMaxCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("TransactionMinCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<int>("WalletContractId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FacilitatorId" }, "IX_WalletContractFacilitator_FacilitatorId");

                    b.HasIndex(new[] { "WalletContractId" }, "IX_WalletContractFacilitator_WalletContractId");

                    b.ToTable("WalletContractFacilitator", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.WalletContractFinancier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("CommissionCalculationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinancierId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FixedAmountCommission")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("FixedPercentageCommission")
                        .HasColumnType("decimal(6, 3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte?>("PaymentMethodType")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("PeriodMaxCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("PeriodMinCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<string>("PortionTypes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieredCommissions")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("TransactionMaxCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("TransactionMinCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<int>("WalletContractId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FinancierId" }, "IX_WalletContractFinancier_FinancierId");

                    b.HasIndex(new[] { "WalletContractId" }, "IX_WalletContractFinancier_WalletContractId");

                    b.ToTable("WalletContractFinancier", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.WalletContractGuarantor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("CommissionCalculationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FixedAmountCommission")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("FixedPercentageCommission")
                        .HasColumnType("decimal(6, 3)");

                    b.Property<int>("GuarantorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte?>("PaymentMethodType")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("PeriodMaxCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("PeriodMinCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<string>("PortionTypes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieredCommissions")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("TransactionMaxCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<decimal?>("TransactionMinCommissionAmount")
                        .HasColumnType("decimal(32, 10)");

                    b.Property<int>("WalletContractId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GuarantorId" }, "IX_WalletContractGuarantor_GuarantorId");

                    b.HasIndex(new[] { "WalletContractId" }, "IX_WalletContractGuarantor_WalletContractId");

                    b.ToTable("WalletContractGuarantor", "Bill");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Billing", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Billing", "Creditor")
                        .WithMany("InverseCreditor")
                        .HasForeignKey("CreditorId");

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Billing", "Debtor")
                        .WithMany("InverseDebtor")
                        .HasForeignKey("DebtorId");

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "FromBusinessIdentity")
                        .WithMany("BillingFromBusinessIdentities")
                        .HasForeignKey("FromBusinessIdentityId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Tenant")
                        .WithMany("Billings")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "ToBusinessIdentity")
                        .WithMany("BillingToBusinessIdentities")
                        .HasForeignKey("ToBusinessIdentityId")
                        .IsRequired();

                    b.Navigation("Creditor");

                    b.Navigation("Debtor");

                    b.Navigation("FromBusinessIdentity");

                    b.Navigation("Tenant");

                    b.Navigation("ToBusinessIdentity");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.BillingPayment", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Billing", "Billing")
                        .WithMany("BillingPayments")
                        .HasForeignKey("BillingId")
                        .IsRequired();

                    b.Navigation("Billing");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Facilitator", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "IdNavigation")
                        .WithOne("Facilitator")
                        .HasForeignKey("Infrastructure.Data.Repository.EfCore.Models.Facilitator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Tenant")
                        .WithMany("Facilitators")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.Navigation("IdNavigation");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.FinancialDocument", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "FromBusinessIdentity")
                        .WithMany("FinancialDocumentFromBusinessIdentities")
                        .HasForeignKey("FromBusinessIdentityId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.MerchantBranch", "MerchantBranch")
                        .WithMany("FinancialDocuments")
                        .HasForeignKey("MerchantBranchId");

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.FinancialDocument", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId");

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Tenant")
                        .WithMany("FinancialDocuments")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.TenantMerchantContract", "TenantMerchantContract")
                        .WithMany("FinancialDocuments")
                        .HasForeignKey("TenantMerchantContractId");

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.TenantPlatformContract", "TenantPlatformContract")
                        .WithMany("FinancialDocuments")
                        .HasForeignKey("TenantPlatformContractId");

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "ToBusinessIdentity")
                        .WithMany("FinancialDocumentToBusinessIdentities")
                        .HasForeignKey("ToBusinessIdentityId")
                        .IsRequired();

                    b.Navigation("FromBusinessIdentity");

                    b.Navigation("MerchantBranch");

                    b.Navigation("Parent");

                    b.Navigation("Tenant");

                    b.Navigation("TenantMerchantContract");

                    b.Navigation("TenantPlatformContract");

                    b.Navigation("ToBusinessIdentity");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Financier", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "IdNavigation")
                        .WithOne("Financier")
                        .HasForeignKey("Infrastructure.Data.Repository.EfCore.Models.Financier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Tenant")
                        .WithMany("Financiers")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.Navigation("IdNavigation");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Guarantor", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "IdNavigation")
                        .WithOne("Guarantor")
                        .HasForeignKey("Infrastructure.Data.Repository.EfCore.Models.Guarantor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Tenant")
                        .WithMany("Guarantors")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.Navigation("IdNavigation");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Installment", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.FinancialDocument", "FinancialDocument")
                        .WithMany("Installments")
                        .HasForeignKey("FinancialDocumentId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "FromBusinessIdentity")
                        .WithMany("InstallmentFromBusinessIdentities")
                        .HasForeignKey("FromBusinessIdentityId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Tenant")
                        .WithMany("Installments")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "ToBusinessIdentity")
                        .WithMany("InstallmentToBusinessIdentities")
                        .HasForeignKey("ToBusinessIdentityId")
                        .IsRequired();

                    b.Navigation("FinancialDocument");

                    b.Navigation("FromBusinessIdentity");

                    b.Navigation("Tenant");

                    b.Navigation("ToBusinessIdentity");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Merchant", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "IdNavigation")
                        .WithOne("Merchant")
                        .HasForeignKey("Infrastructure.Data.Repository.EfCore.Models.Merchant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.MerchantBilling", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Billing", "IdNavigation")
                        .WithOne("MerchantBilling")
                        .HasForeignKey("Infrastructure.Data.Repository.EfCore.Models.MerchantBilling", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.MerchantBranch", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "IdNavigation")
                        .WithOne("MerchantBranch")
                        .HasForeignKey("Infrastructure.Data.Repository.EfCore.Models.MerchantBranch", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Merchant", "Merchant")
                        .WithMany("MerchantBranches")
                        .HasForeignKey("MerchantId")
                        .IsRequired();

                    b.Navigation("IdNavigation");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.MerchantInstallment", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Installment", "IdNavigation")
                        .WithOne("MerchantInstallment")
                        .HasForeignKey("Infrastructure.Data.Repository.EfCore.Models.MerchantInstallment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.TenantMerchantContract", "TenantMerchantContract")
                        .WithMany("MerchantInstallments")
                        .HasForeignKey("TenantMerchantContractId")
                        .IsRequired();

                    b.Navigation("IdNavigation");

                    b.Navigation("TenantMerchantContract");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Organization", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "IdNavigation")
                        .WithOne("Organization")
                        .HasForeignKey("Infrastructure.Data.Repository.EfCore.Models.Organization", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Organization", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId");

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Tenant")
                        .WithMany("Organizations")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.Navigation("IdNavigation");

                    b.Navigation("Parent");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Tenant", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", "IdNavigation")
                        .WithOne("Tenant")
                        .HasForeignKey("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantIpgSetting", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Tenant")
                        .WithMany("TenantIpgSettings")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantMerchantContract", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Merchant", "Merchant")
                        .WithMany("TenantMerchantContracts")
                        .HasForeignKey("MerchantId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.TenantMerchantContract", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId");

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Tenant")
                        .WithMany("TenantMerchantContracts")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("Parent");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantPlatformContract", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Tenant")
                        .WithMany("TenantPlatformContracts")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.TenantIpgSetting", "TenantIpgSetting")
                        .WithMany("TenantPlatformContracts")
                        .HasForeignKey("TenantIpgSettingId")
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("TenantIpgSetting");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantPlatformContractFacilitator", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Facilitator", "Facilitator")
                        .WithMany("TenantPlatformContractFacilitators")
                        .HasForeignKey("FacilitatorId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.TenantPlatformContract", "TenantPlatformContract")
                        .WithMany("TenantPlatformContractFacilitators")
                        .HasForeignKey("TenantPlatformContractId")
                        .IsRequired();

                    b.Navigation("Facilitator");

                    b.Navigation("TenantPlatformContract");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantPlatformContractProvider", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Provider", "Provider")
                        .WithMany("TenantPlatformContractProviders")
                        .HasForeignKey("ProviderId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.TenantPlatformContract", "TenantPlatformContract")
                        .WithMany("TenantPlatformContractProviders")
                        .HasForeignKey("TenantPlatformContractId")
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("TenantPlatformContract");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.WalletContract", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Tenant", "Tenant")
                        .WithMany("WalletContracts")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.TenantIpgSetting", "TenantIpgSetting")
                        .WithMany("WalletContracts")
                        .HasForeignKey("TenantIpgSettingId");

                    b.Navigation("Tenant");

                    b.Navigation("TenantIpgSetting");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.WalletContractFacilitator", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Facilitator", "Facilitator")
                        .WithMany("WalletContractFacilitators")
                        .HasForeignKey("FacilitatorId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.WalletContract", "WalletContract")
                        .WithMany("WalletContractFacilitators")
                        .HasForeignKey("WalletContractId")
                        .IsRequired();

                    b.Navigation("Facilitator");

                    b.Navigation("WalletContract");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.WalletContractFinancier", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Financier", "Financier")
                        .WithMany("WalletContractFinanciers")
                        .HasForeignKey("FinancierId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.WalletContract", "WalletContract")
                        .WithMany("WalletContractFinanciers")
                        .HasForeignKey("WalletContractId")
                        .IsRequired();

                    b.Navigation("Financier");

                    b.Navigation("WalletContract");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.WalletContractGuarantor", b =>
                {
                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.Guarantor", "Guarantor")
                        .WithMany("WalletContractGuarantors")
                        .HasForeignKey("GuarantorId")
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Repository.EfCore.Models.WalletContract", "WalletContract")
                        .WithMany("WalletContractGuarantors")
                        .HasForeignKey("WalletContractId")
                        .IsRequired();

                    b.Navigation("Guarantor");

                    b.Navigation("WalletContract");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Billing", b =>
                {
                    b.Navigation("BillingPayments");

                    b.Navigation("InverseCreditor");

                    b.Navigation("InverseDebtor");

                    b.Navigation("MerchantBilling");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.BusinessIdentity", b =>
                {
                    b.Navigation("BillingFromBusinessIdentities");

                    b.Navigation("BillingToBusinessIdentities");

                    b.Navigation("Facilitator");

                    b.Navigation("FinancialDocumentFromBusinessIdentities");

                    b.Navigation("FinancialDocumentToBusinessIdentities");

                    b.Navigation("Financier");

                    b.Navigation("Guarantor");

                    b.Navigation("InstallmentFromBusinessIdentities");

                    b.Navigation("InstallmentToBusinessIdentities");

                    b.Navigation("Merchant");

                    b.Navigation("MerchantBranch");

                    b.Navigation("Organization");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Facilitator", b =>
                {
                    b.Navigation("TenantPlatformContractFacilitators");

                    b.Navigation("WalletContractFacilitators");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.FinancialDocument", b =>
                {
                    b.Navigation("Installments");

                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Financier", b =>
                {
                    b.Navigation("WalletContractFinanciers");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Guarantor", b =>
                {
                    b.Navigation("WalletContractGuarantors");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Installment", b =>
                {
                    b.Navigation("MerchantInstallment");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Merchant", b =>
                {
                    b.Navigation("MerchantBranches");

                    b.Navigation("TenantMerchantContracts");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.MerchantBranch", b =>
                {
                    b.Navigation("FinancialDocuments");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Organization", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Provider", b =>
                {
                    b.Navigation("TenantPlatformContractProviders");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.Tenant", b =>
                {
                    b.Navigation("Billings");

                    b.Navigation("Facilitators");

                    b.Navigation("FinancialDocuments");

                    b.Navigation("Financiers");

                    b.Navigation("Guarantors");

                    b.Navigation("Installments");

                    b.Navigation("Organizations");

                    b.Navigation("TenantIpgSettings");

                    b.Navigation("TenantMerchantContracts");

                    b.Navigation("TenantPlatformContracts");

                    b.Navigation("WalletContracts");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantIpgSetting", b =>
                {
                    b.Navigation("TenantPlatformContracts");

                    b.Navigation("WalletContracts");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantMerchantContract", b =>
                {
                    b.Navigation("FinancialDocuments");

                    b.Navigation("InverseParent");

                    b.Navigation("MerchantInstallments");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.TenantPlatformContract", b =>
                {
                    b.Navigation("FinancialDocuments");

                    b.Navigation("TenantPlatformContractFacilitators");

                    b.Navigation("TenantPlatformContractProviders");
                });

            modelBuilder.Entity("Infrastructure.Data.Repository.EfCore.Models.WalletContract", b =>
                {
                    b.Navigation("WalletContractFacilitators");

                    b.Navigation("WalletContractFinanciers");

                    b.Navigation("WalletContractGuarantors");
                });
#pragma warning restore 612, 618
        }
    }
}
