<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Events\**" />
    <EmbeddedResource Remove="Events\**" />
    <None Remove="Events\**" />
  </ItemGroup>

  

  <ItemGroup>
    <ProjectReference Include="..\Domain.Core\Domain.Core.csproj" />
    <ProjectReference Include="..\Shared.EventBus\Shared.EventBus.csproj" />
    <ProjectReference Include="..\Shared.FluentValidation\Shared.FluentValidation.csproj" />
    <ProjectReference Include="..\Shared.MediatR\Shared.MediatR.csproj" />

  </ItemGroup>

  

  <ItemGroup>
    <Folder Include="NewFolder\" />
  </ItemGroup>

</Project>
