<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<UserSecretsId>841d42bb-087f-4f05-836f-17b708c85194</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Shared.ApiVersioning" Version="251125.530.25" />
		<PackageReference Include="Shared.Logging.Serilog" Version="251125.530.25" />
		<PackageReference Include="Shared.Middlewares" Version="251125.530.25" />
		<PackageReference Include="Shared.Swagger" Version="251125.530.25" />

    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.12.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.12.0" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\Application.Command\Application.Command.csproj" />
		<ProjectReference Include="..\Application.Query\Application.Query.csproj" />
		<ProjectReference Include="..\Application.Service\Application.Service.csproj" />
		<ProjectReference Include="..\Infrastructure.Data.Repository.EfCore\Infrastructure.Data.Repository.EfCore.csproj" />

	</ItemGroup>


	<ItemGroup>
	  <Folder Include="V1\RequestModels\Merchants\" />
	</ItemGroup>

</Project>
